sudo: false
language: generic
env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
    - GHRAW="https://raw.githubusercontent.com"
  matrix:
  - EMACS_VERSION=25.1
  # 25.2 is identical to 25.3 except for a critical security bug in
  # enriched text mode (see Emacs Bug#28350).
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=26     # 26.1.50, emacs-26 branch, built daily
  - EMACS_VERSION=master # 27.0.50, master branch, built daily
  allow_failures:
    - env: EMACS_VERSION=master
install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $EMACS -Q --batch --load .travis.el
  - $EMACS --version
script:
  - git config --global user.name "A U Thor"
  - git config --global user.email a.u.thor@example.com
  - git tag 0
  - make lisp EMACSBIN=$EMACS
  - make test EMACSBIN=$EMACS
notifications:
  email:
    # Default is change, but that includes a new branch's 1st success.
    on_success: never
    on_failure: always # The default.
